name: CI - Laravel PHPStan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  phpstan:
    name: Run PHPStan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Create .env file
        run: cp .env.test .env

      - name: Create Database
        run: touch ./database/database.sqlite
        
      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Run migrations
        run: php artisan migrate 

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --memory-limit=512M

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit 
 